FROM ubuntu:20.04

LABEL maintainer="Assa.Toolex@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

COPY conf/ /conf
COPY tools/ /tools
COPY var-www-html/ /var/www/html

# wget curl sudo mc tcpdump git openssh-server openssl
# python3-venv python3-distutils python3-pyasn1 python3-pyasn1-modules python3-ldap python3-pygraphviz 
#

RUN \
    apt-get --quiet --yes update && \
    apt-get --yes --no-install-recommends install \
        bash nano nginx squid make gettext \
        openssh-client \
        python3-minimal python3-pip python3-setuptools python3-wheel \
        python3-virtualenv \
        pypy3 \
        redis-server tor && \
    apt-get --quiet --yes upgrade && apt-get --quiet --yes autoremove && apt-get clean && \
    chmod +x /conf/*.sh && \
    echo "Skel fix..." && mkdir -p /etc/skel/.ssh && touch /etc/skel/.ssh/authorized_keys && \
    cd /tools/modules/sshd && make pip_install_cpython3

CMD /conf/entrypoint.sh
